name = "autorag-test"
main = "test-autorag.js"
compatibility_date = "2024-12-30"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_DOCUMENTS"
bucket_name = "buildmantle-rag-documents"

# AutoRAG store binding
[[autorag_stores]]
binding = "AUTORAG"
store_name = "buildmantletest"
r2_source = "R2_DOCUMENTS"

# AI binding for fallback
[ai]
binding = "AI"