-- Seed data for tasks table  
-- Note: These tasks are associated with the demo user (pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP)

INSERT INTO "task" ("id", "userId", "title", "description", "status", "label", "priority", "assignee", "dueDate", "createdAt", "updatedAt") VALUES
('TASK-1001', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Setup Development Environment', 'Install and configure all necessary development tools and dependencies', 'done', 'feature', 'high', 'John Doe', NULL, strftime('%s', 'now', '-7 days'), strftime('%s', 'now', '-1 day')),
('TASK-1002', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Design Database Schema', 'Create comprehensive database schema for the application', 'done', 'feature', 'high', 'Jane Smith', NULL, strftime('%s', 'now', '-6 days'), strftime('%s', 'now', '-2 days')),
('TASK-1003', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Implement User Authentication', 'Set up Better Auth with OAuth providers (Google, GitHub)', 'in progress', 'feature', 'critical', 'John Doe', strftime('%s', 'now', '+3 days'), strftime('%s', 'now', '-5 days'), strftime('%s', 'now', '-1 hour')),
('TASK-1004', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Create API Endpoints', 'Build REST API endpoints for CRUD operations', 'in progress', 'feature', 'high', 'Bob Wilson', strftime('%s', 'now', '+5 days'), strftime('%s', 'now', '-4 days'), strftime('%s', 'now', '-30 minutes')),
('TASK-1005', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Fix Login Bug', 'Users cannot login with special characters in password', 'todo', 'bug', 'high', 'Jane Smith', strftime('%s', 'now', '+2 days'), strftime('%s', 'now', '-3 days'), strftime('%s', 'now', '-3 days')),
('TASK-1006', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Write API Documentation', 'Create comprehensive API documentation using OpenAPI/Swagger', 'todo', 'documentation', 'medium', 'Alice Johnson', strftime('%s', 'now', '+7 days'), strftime('%s', 'now', '-2 days'), strftime('%s', 'now', '-2 days')),
('TASK-1007', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Implement Dark Mode', 'Add dark mode support across the application', 'todo', 'feature', 'low', 'Charlie Brown', strftime('%s', 'now', '+10 days'), strftime('%s', 'now', '-1 day'), strftime('%s', 'now', '-1 day')),
('TASK-1008', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Setup CI/CD Pipeline', 'Configure automated testing and deployment pipeline', 'backlog', 'feature', 'medium', NULL, NULL, strftime('%s', 'now', '-1 day'), strftime('%s', 'now', '-1 day')),
('TASK-1009', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Performance Optimization', 'Optimize application performance and loading times', 'backlog', 'feature', 'medium', NULL, NULL, strftime('%s', 'now', '-1 day'), strftime('%s', 'now', '-1 day')),
('TASK-1010', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Fix Mobile Responsiveness', 'Dashboard not displaying correctly on mobile devices', 'todo', 'bug', 'medium', 'Diana Prince', strftime('%s', 'now', '+4 days'), strftime('%s', 'now', '-6 hours'), strftime('%s', 'now', '-6 hours')),
('TASK-1011', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Add Data Export Feature', 'Allow users to export their data in CSV/JSON format', 'backlog', 'feature', 'low', NULL, NULL, strftime('%s', 'now', '-12 hours'), strftime('%s', 'now', '-12 hours')),
('TASK-1012', 'pWCD43Y7W24ZwHXNZOnbfeocUXtlE5gP', 'Security Audit', 'Conduct comprehensive security audit of the application', 'canceled', 'feature', 'critical', 'Frank Castle', NULL, strftime('%s', 'now', '-10 days'), strftime('%s', 'now', '-8 days'));